
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iam-apiserver
  name: iam-apiserver
  namespace: default
spec:
  clusterIP: 192.168.0.231 # è™šæ‹ŸæœåŠ¡åœ°å€
  externalTrafficPolicy: Cluster # è¡¨ç¤ºæ­¤æœåŠ¡æ˜¯å¦å¸Œæœ›å°†å¤–éƒ¨æµé‡è·¯ç”±åˆ°èŠ‚ç‚¹æœ¬åœ°æˆ–é›†ç¾¤èŒƒå›´çš„ç«¯ç‚?  ports: # serviceéœ€è¦æš´éœ²çš„ç«¯å£åˆ—è¡¨
  - name: https #ç«¯å£åç§°
    nodePort: 30443 # å½“type = NodePortæ—¶ï¼ŒæŒ‡å®šæ˜ å°„åˆ°ç‰©ç†æœºçš„ç«¯å£å·
    port: 8443 # æœåŠ¡ç›‘å¬çš„ç«¯å£å·
    protocol: TCP # ç«¯å£åè®®ï¼Œæ”¯æŒTCPå’ŒUDPï¼Œé»˜è®¤TCP
    targetPort: 8443 # éœ€è¦è½¬å‘åˆ°åç«¯Podçš„ç«¯å£å·
  selector: # label selectoré…ç½®ï¼Œå°†é€‰æ‹©å…·æœ‰labelæ ‡ç­¾çš„Podä½œä¸ºå…¶åç«¯RS
    app: iam-apiserver
  sessionAffinity: None # æ˜¯å¦æ”¯æŒsession
  type: NodePort # serviceçš„ç±»å‹ï¼ŒæŒ‡å®šserviceçš„è®¿é—®æ–¹å¼ï¼Œé»˜è®¤ä¸ºclusterIp
